language: node_js
node_js:
  - 7
  - 8
  - node

before_script:
  - openssl aes-256-cbc -K $encrypted_2175655a206c_key -iv $encrypted_2175655a206c_iv -in id_rsa.enc -out id_rsa -d

script:
  - npm run lint
  - npm run unit-test
